import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    docs: [
        'introduction',
        {
            type: 'category',
            label: 'Getting Started',
            link: {
                type: 'generated-index',
            },
            collapsed: false,
            items: [
                'installation',
                'first-time-setup',
            ],
        },
        {
            type: 'category',
            label: 'Guides',
            link: {
                type: 'generated-index',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'guides',
                }
            ]
        },
        {
            type: 'category',
            label: 'Contributing',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'contributing',
                }
            ]
        },
        {
            type: 'category',
            label: 'FAQ',
            link: {
                type: 'generated-index',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'faq',
                }
            ]

        }
    ]
};

export default sidebars;
